# Generated by Django 5.1.7 on 2025-03-18 17:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(help_text="菜单Code", max_length=255)),
                ("name", models.CharField(help_text="菜单名称", max_length=255)),
                (
                    "is_show",
                    models.CharField(
                        default="ALL", help_text="根据角色显示", max_length=50
                    ),
                ),
                ("path", models.CharField(help_text="path", max_length=255)),
                (
                    "parent_code",
                    models.CharField(
                        default="0", help_text="菜单父节点", max_length=255
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, help_text="菜单排序")),
            ],
            options={
                "db_table": "menu",
            },
        ),
    ]
