# Generated by Django 5.1.7 on 2025-03-19 05:31

import src.apps.Animal_display.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Animal_display", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal_information",
            name="img",
            field=models.ImageField(
                help_text="动物图片",
                upload_to=src.apps.Animal_display.models.animal_image_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="animal_information",
            name="status",
            field=models.CharField(
                default="active", help_text="动物状态", max_length=24
            ),
        ),
    ]
