# Generated by Django 5.1.7 on 2025-03-18 17:25

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "username",
                    models.CharField(help_text="用户名", max_length=30, unique=True),
                ),
                ("password", models.CharField(help_text="用户密码", max_length=30)),
                ("name", models.CharField(help_text="用户姓名", max_length=30)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("common_user", "Common_user"),
                            ("admin", "Admin"),
                            ("super_admin", "Super_admin"),
                        ],
                        default="common_user",
                        help_text="角色名",
                        max_length=20,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        default="male",
                        help_text="性别",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, help_text="是否激活")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, help_text="是否删除"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="电话号码", max_length=20, null=True
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, help_text="邮箱账号", max_length=255, null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="更新时间"),
                ),
                (
                    "admin_id",
                    models.CharField(
                        help_text="管理员编号", max_length=30, unique=True
                    ),
                ),
            ],
            options={
                "db_table": "admin",
            },
        ),
        migrations.CreateModel(
            name="Common_user",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "username",
                    models.CharField(help_text="用户名", max_length=30, unique=True),
                ),
                ("password", models.CharField(help_text="用户密码", max_length=30)),
                ("name", models.CharField(help_text="用户姓名", max_length=30)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("common_user", "Common_user"),
                            ("admin", "Admin"),
                            ("super_admin", "Super_admin"),
                        ],
                        default="common_user",
                        help_text="角色名",
                        max_length=20,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        default="male",
                        help_text="性别",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, help_text="是否激活")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, help_text="是否删除"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="电话号码", max_length=20, null=True
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, help_text="邮箱账号", max_length=255, null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="更新时间"),
                ),
                (
                    "common_user_id",
                    models.CharField(help_text="用户编号", max_length=30, unique=True),
                ),
            ],
            options={
                "db_table": "common_user",
            },
        ),
    ]
