# Generated by Django 5.1.7 on 2025-03-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserManagement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="points",
            field=models.IntegerField(default=0, help_text="积分"),
        ),
        migrations.AddField(
            model_name="common_user",
            name="points",
            field=models.IntegerField(default=0, help_text="积分"),
        ),
        migrations.AlterField(
            model_name="admin",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="创建时间"),
        ),
        migrations.AlterField(
            model_name="common_user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="创建时间"),
        ),
    ]
