# Generated by Django 5.1.7 on 2025-03-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task_information",
            name="deadline",
            field=models.DateTimeField(blank=True, help_text="任务截止时间", null=True),
        ),
        migrations.AddField(
            model_name="task_information",
            name="is_published",
            field=models.BooleanField(default=False, help_text="任务是否已发布"),
        ),
        migrations.AddField(
            model_name="task_information",
            name="publish_time",
            field=models.DateTimeField(blank=True, help_text="任务发布时间", null=True),
        ),
        migrations.AddField(
            model_name="task_information",
            name="task_publisher_id",
            field=models.CharField(
                default=0, help_text="任务发布管理员编号", max_length=20
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task_information",
            name="task_taker_id",
            field=models.CharField(
                default="None", help_text="任务接取人编号", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="task_information",
            name="status",
            field=models.CharField(
                choices=[
                    ("未被接取", "未被接取"),
                    ("未完成", "未完成"),
                    ("进行中", "进行中"),
                    ("确认完成", "确认完成"),
                    ("已逾期", "已逾期"),
                    ("已完成，待确认", "已完成，待确认"),
                    ("被驳回", "被驳回"),
                ],
                default="未完成",
                help_text="任务状态",
                max_length=20,
            ),
        ),
    ]
