# Generated by Django 5.1.7 on 2025-03-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tasks", "0003_alter_task_information_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task_information",
            name="status",
            field=models.CharField(
                choices=[
                    ("未发布", "未发布"),
                    ("未被接取", "未被接取"),
                    ("未完成", "未完成"),
                    ("进行中", "进行中"),
                    ("确认完成", "确认完成"),
                    ("已逾期", "已逾期"),
                    ("已完成，待确认", "已完成，待确认"),
                    ("被驳回", "被驳回"),
                ],
                default="未被接取",
                help_text="任务状态",
                max_length=20,
            ),
        ),
    ]
